Repository hashtopolis/server, pull requests merged in 2022-06, with the labels that each got.

#758 Notifications do not honor access settings
  src/inc/defines/notifications.php
  src/inc/handlers/NotificationHandler.class.php
  src/inc/utils/HashlistUtils.class.php
Labels: bug

#764 Add support for maximum amount of agents that should work on a task.
  ci/run.php
  ci/tests/PretaskTest.class.php
  ci/tests/TaskTest.class.php
  ci/tests/integration/MaxAgentsTest.class.php
  doc/user-api/sections/pretask.tex
  doc/user-api/sections/task.tex
  src/ajax/get_subtasks.php
  src/dba/models/Pretask.class.php
  src/dba/models/PretaskFactory.class.php
  src/dba/models/Task.class.php
  src/dba/models/TaskFactory.class.php
  src/dba/models/generator.php
  src/inc/Util.class.php
  src/inc/api/APIGetChunk.class.php
  src/inc/api/APIGetTask.class.php
  src/inc/defines/tasks.php
  src/inc/defines/userApi.php
  src/inc/handlers/PretaskHandler.class.php
  src/inc/handlers/TaskHandler.class.php
  src/inc/user-api/UserAPIPretask.class.php
  src/inc/user-api/UserAPITask.class.php
  src/inc/utils/HashlistUtils.class.php
  src/inc/utils/PretaskUtils.class.php
  src/inc/utils/SupertaskUtils.class.php
  src/inc/utils/TaskUtils.class.php
  src/install/hashtopolis.sql
  src/install/updates/update_v0.12.x_v0.x.x.php
  src/templates/pretasks/detail.template.html
  src/templates/pretasks/index.template.html
  src/templates/tasks/detail.template.html
  src/templates/tasks/index.template.html
  src/templates/tasks/new.template.html
  src/templates/tasks/normal.template.html
  src/templates/tasks/subtasks.template.html
  src/templates/tasks/supertask.template.html
Labels: new feature

#766 Change access group for hashlist not working
  doc/changelog.md
  src/inc/utils/HashlistUtils.class.php
Labels: bug

#770 Fixed sending two to headers when sending email.
  doc/changelog.md
  src/inc/Util.class.php
Labels: bug

#775 Detecting Microsoft GPU correctly and making voucher persist in devcontainer
  .devcontainer/adduser.php
  src/inc/api/APIUpdateClientInformation.class.php
Labels: enhancement

#780 DevContainer not starting when DEV_CONTAINER_USER_CMD is not set
  .devcontainer/Dockerfile
Labels: bug

#788 Changing permissions and default user for devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
Labels: bug

#789 Failed to delete hashlist containing cracked hashes while agent is running on the hashlist
  doc/changelog.md
  src/inc/utils/HashlistUtils.class.php
Labels: bug
