Repository hashtopolis/server, pull requests merged in 2023-08, with the labels that each got.

#798 check for non-required values in user API createTask command
  src/inc/user-api/UserAPITask.class.php
Labels: enhancement

#967 [BUG] fixed all issue templates to changes of github
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/BUG.yml
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.yml
  .github/ISSUE_TEMPLATE/EPIC.md
  .github/ISSUE_TEMPLATE/EPIC.yml
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/ISSUE_TEMPLATE/FEATURE.yml
Labels: doc

#813 Add support for maximum amount of agents that should work on a supertask
  ci/tests/integration/MaxAgentsTest.class.php
  doc/changelog.md
  doc/user-api/sections/task.tex
  src/dba/models/TaskWrapper.class.php
  src/dba/models/TaskWrapperFactory.class.php
  src/dba/models/generator.php
  src/inc/Util.class.php
  src/inc/defines/tasks.php
  src/inc/defines/userApi.php
  src/inc/handlers/PretaskHandler.class.php
  src/inc/handlers/SupertaskHandler.class.php
  src/inc/handlers/TaskHandler.class.php
  src/inc/user-api/UserAPIPretask.class.php
  src/inc/user-api/UserAPITask.class.php
  src/inc/utils/HashlistUtils.class.php
  src/inc/utils/PretaskUtils.class.php
  src/inc/utils/SupertaskUtils.class.php
  src/inc/utils/TaskUtils.class.php
  src/install/hashtopolis.sql
  src/install/updates/update_v0.14.0_v0.x.x.php
  src/templates/supertasks/import.template.html
  src/templates/supertasks/index.template.html
  src/templates/tasks/supertask.template.html
Labels: new feature
